language: python
python:
    - 3.5 # tox handles others versions with virtualenvs
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy3

install:
  - pip3 install -U tox

script:
  - tox
