#!/bin/bash

set -e

VENV=".venv"
DIR="$(dirname $(readlink "$0"))"
VENVDIR="${DIR}/${VENV}"
ACTIVATE="${VENVDIR}/bin/activate"

if [ ! -f $ACTIVATE ]; then
    echo "sieve-git-pushdeploy error, virtualenv not found at ${VENVDIR}!"
    echo "Please consult README.md."
    exit 1
fi

source $ACTIVATE
exec $DIR/post-receive.py


